### ISSUE TITLE
Windows machines cannot read/write XML files

### ISSUE THREAD

**Issue by janez33** [ragibson/SMS-MMS-deduplication#9] opened 2024-11-15 08:54 UTC
Hello, how to fix this? :(

![image](https://github.com/user-attachments/assets/319df2ae-b885-4a26-948a-74e366ea9221)

**Comment by ragibson** [comment] 2024-11-15 13:11
I think this is a duplicate of https://github.com/ragibson/SMS-MMS-deduplication/issues/8 since the error is occurring in lxml itself.

Very large elements in the XML tree seem to crash the XML parsers available in Python.

**Comment by janez33** [comment] 2024-11-15 21:42
WORKING!
I was on Windows 10.
Now I switched to Linux and voila! It works :) 
![slika](https://github.com/user-attachments/assets/faa95b6f-3b7b-4906-803c-cc6a432c97d7)

**Comment by gazpachoking** [comment] 2024-12-05 23:14
I managed to fix this on windows by explicitly opening the file rather than passing a filename to lxml. Had to do it both for reading and writing the file back to disk.

**Comment by ragibson** [comment] 2024-12-05 23:26
> I managed to fix this on windows by explicitly opening the file rather than passing a filename to lxml.

Very strange, does this happen with every input file or just large ones (e.g., one of the tiny ones in the `tests/` directory)?

I'll try and replicate this in a few days when I have access to a Windows machine.

**Comment by ragibson** [comment] 2024-12-08 23:03
Replicated, even for some files of a few GB that do _not_ crash the standard library parser.

It seems Windows simply performs much worse than Linux here and crashes some of the lxml internals.

**Closed** 2024-12-08 23:55 UTC
